### ISSUE TITLE
Verified but my NFTs don't show project and yellow ticks.

### ISSUE THREAD

**Issue by NationsADA** [Cardano-NFTs/policyIDs#1885]
I got merged today but my NFTs show unknown project and dont have a yellow tick? Is this going to be shown in a while? Is there something i did wrong?

**Comment by cardanomushrooms** [comment]
Same case with our CNFTs. Not showing in "Verified" list in filter nor returning any result in marketplace search results and showing "unknown" in an CNFT details.

**Comment by NationsADA** [comment]
Hope we dont have a week of waiting ahead of us. The CNFT ecosystem needs more instructions for us trying to use it. Also we have to step up our game with minters and marketplaces otherwise we will be overtaken by Solana. We cant always be into uncertainty because we dont have enough information about how to do stuff.

**Comment by cardanomushrooms** [comment]
Well, it looks like CNFT.io guys are either not committed to smaller projects or either their system is not as efficient as it needs to be. Imagine waiting for days and weeks to get your PR to be merged only later to be found useless because you still might not get a verified tick-mark. It is relatively a straight forward and simple thing to do. We wonder why they designed a stupid system just for verification. We had a better experience with Tokhun.io as they only took a couple of hours to approve our project. There are some other platform, too. If they keep on just running after big projects and keep ignoring the smaller one, eventually people will start shifting to other better platform. Because it is ridiculous how they don't even care to respond to queries in a professional manner.

**Comment by NationsADA** [comment]
Also here is our merged pull request.
https://github.com/Cardano-NFTs/policyIDs/pull/1822

**Comment by cardanomushrooms** [comment]
> Also here is our merged pull request. #1822

Yes, checked and searched yours on the website, too, but it is not showing in search results.

**Comment by NationsADA** [comment]
We are not listing yet. I just test listed 1 min ago. I am waiting for the verification to list em. The thing is we are investing money and time and therefore the time we are losing now its valuable.

**Comment by cardanomushrooms** [comment]
> We are not listing yet. I just test listed 1 min ago. I am waiting for the verification to list em. The thing is we are investing money and time and therefore the time we are losing now is valuable.

Agree. You should try Tokhun.io, too. They are quick on verifying process. Better to use as many platform as many we can.

**Comment by NationsADA** [comment]
We are believing in a central platform for NFTs and as long as the larger one CNFT.io is working we won't try to leave. We might do it if we don't have any other choice though.

**Comment by cardanomushrooms** [comment]
> We are believing in a central platform for NFTs and as long as the larger one CNFT.io is working we won't try to leave. We might do it if we don't have any other choice though.

Good luck.

**Comment by NationsADA** [comment]
Alright after communication CNFT.io solved the problem.
