### ISSUE TITLE
Pull Request #1670

### ISSUE THREAD

**Issue by ICSRocketShop** [Cardano-NFTs/policyIDs#2048]
Please let me know if it's something wrong with #1670 request.

Thank you!

**Comment by Dado202** [comment]
Nobody will answer you. Im waiting too. I dont know what is wrong with my project #1741

**Comment by JakeAdlerWriter** [comment]
3 weeks and counting for me.  I've since stopped checking daily and won't use cnft.io website any further until (if) this site sorts out its marketing and verification process of projects.  At the moment, waiting for a competitor to offer a proper service elsewhere.

**Comment by Dado202** [comment]
What, other site we can take??

**Comment by Dado202** [comment]
Find me on tweeter MyFirstMillion x Bull VS Bear. Send me mesaages

**Comment by JakeAdlerWriter** [comment]
Well, firstly a better question is whether cnft.io actually uses smart contracts.  I think (if) they did, they are badly designed - hence the need for such manual labour in verifying everything (which they don't do much of, except with bigger projects - leaving the rest to rot and be invisible).  The second is, is ADA truly operable with smart contracts or does it crash?  See here for cnftio crashes due to volume. https://forum.cardano.org/t/cnft-io-down/76667  we may have to wait for the next update of ADA for this whole NFT thing to work better....or a competitor to write better smart contracts.

**Comment by Dado202** [comment]
The problem is that nobody write on pull request what is wrong. Just that.
